name: buxdotph
description: A dart client for bux.ph api. This client makes it simple for
  developers to start accepting payment with bux.ph
version: 0.0.11
homepage: "https://goldcoders.dev"
repository: "https://github.com/goldcoders/buxdotph"

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  collection: ^1.15.0
  dartz: ^0.10.0
  equatable: ^2.0.3
  http: ^0.13.4

dev_dependencies:
  dotenv: ^3.0.0
  lint: ^1.5.2
  mocktail: ^0.2.0
  test: ^1.19.5
